# Generated by Django 5.2.12 on 2026-04-04 12:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChatHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_id",
                    models.CharField(max_length=64, verbose_name="用户ID（IP生成）"),
                ),
                (
                    "character",
                    models.CharField(
                        choices=[("kaltsit", "凯尔希")],
                        default="kaltsit",
                        max_length=32,
                        verbose_name="对话角色",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("user", "博士"), ("assistant", "角色")],
                        max_length=16,
                        verbose_name="发言角色",
                    ),
                ),
                ("content", models.TextField(verbose_name="对话内容")),
                (
                    "create_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="创建时间"
                    ),
                ),
            ],
            options={
                "verbose_name": "对话历史",
                "verbose_name_plural": "对话历史",
                "ordering": ["create_time"],
            },
        ),
    ]
