# Generated by Django 4.2.10 on 2026-04-27 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaltsit_chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chathistory',
            name='character',
            field=models.CharField(default='kaltsit', max_length=32, verbose_name='对话角色'),
        ),
        migrations.AlterField(
            model_name='chathistory',
            name='role',
            field=models.CharField(choices=[('user', '博士'), ('assistant', '凯尔希')], max_length=16, verbose_name='发言角色'),
        ),
        migrations.AlterField(
            model_name='chathistory',
            name='user_id',
            field=models.CharField(max_length=64, verbose_name='用户ID'),
        ),
        migrations.AddIndex(
            model_name='chathistory',
            index=models.Index(fields=['user_id', 'character'], name='kaltsit_cha_user_id_ebfb20_idx'),
        ),
        migrations.AddIndex(
            model_name='chathistory',
            index=models.Index(fields=['create_time'], name='kaltsit_cha_create__d5f613_idx'),
        ),
    ]
